<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <!--If you are willing to use Windows/MacOS native APIs you will need to create 3 projects.
    One for Windows with net7.0-windows TFM, one for MacOS with net7.0-macos and one with net7.0 TFM for Linux.-->
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="12.0.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.3.9" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
    <PackageReference Include="LiveMarkdown.Avalonia" Version="2.4.1" />
    <PackageReference Include="LiveMarkdown.Avalonia.Math" Version="2.4.1" />
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.10.0" />
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="11.0.0-rc.1.26425.128" />
    <PackageReference Include="Microsoft.VisualStudio.Threading" Version="18.7.23" />
    <PackageReference Include="Svg.Controls.Skia.Avalonia" Version="12.0.0.17" />
    <PackageReference Include="Svg.Skia" Version="5.2.3" />
    <PackageReference Include="System.IO.Hashing" Version="11.0.0-rc.1.26425.128" />
    <PackageReference Include="System.Text.Json" Version="11.0.0-rc.1.26425.128" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AjkAvaloniaLibs\AjkAvaloniaLibs\AjkAvaloniaLibs.csproj" />
    <ProjectReference Include="..\CodeEditor2AiPlugin\CodeEditor2AiPlugin\CodeEditor2AiPlugin.csproj" />
    <ProjectReference Include="..\CodeEditor2DrawIoPlugin\CodeEditor2DrawIoPlugin\CodeEditor2DrawIoPlugin.csproj" />
    <ProjectReference Include="..\CodeEditor2IcarusVerilogPlugin\CodeEditor2IcarusVerilogPlugin\CodeEditor2IcarusVerilogPlugin.csproj" />
    <ProjectReference Include="..\CodeEditor2MarkdownPlugin\CodeEditor2MarkdownPlugin\CodeEditor2MarkdownPlugin.csproj" />
    <ProjectReference Include="..\CodeEditor2Plugin\CodeEditor2Plugin\CodeEditor2Plugin\CodeEditor2Plugin.csproj" />
    <ProjectReference Include="..\CodeEditor2VerilogPlugin\CodeEditor2VerilogPlugin\CodeEditor2VerilogPlugin.csproj" />
    <ProjectReference Include="..\CodeEditor2VivadoPlugin\CodeEditor2VivadoPlugin\CodeEditor2VivadoPlugin.csproj" />
    <ProjectReference Include="..\CodeEditor2\CodeEditor2\CodeEditor2.csproj" />
  </ItemGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Views\LLMAgentWindow.axaml.cs">
	    <DependentUpon>LLMAgentWindow.axaml</DependentUpon>
	  </Compile>
	</ItemGroup>
	<PropertyGroup>
		<ApplicationIcon>Assets/RtlEditor.ico</ApplicationIcon>
	</PropertyGroup>
	
</Project>
